### ISSUE TITLE
Enable setting OMS Workspace

### ISSUE THREAD

**Issue by russellds** [Microsoft/Azure-Security-Center#4]
Is it possible to enable setting the OMS Workspace? I have tried directly modifying the JSON file to specify a specific OMS Workspace but Set-ASCPolicy throws an error. Not sure if the error is because of the module or the ASC REST API.

**Comment by Javanite** [comment]
@russellds  Putting a response here even though we are talking about this via email.

Currently there is no

**Comment by Javanite** [comment]
Investigating options to add an OMS Workspace parameter to Build-ASCPolicy. The ASC Rest API documentation doesn't provide guidance around this, which is why I didn't add it. I'll add this to my backlog of to-do's once I get confirmation from engineering that we can set this property via API.

**Comment by Javanite** [comment]
After talking with engineering, they explained that you cannot change the OMS Workspace property using the ASC API's. This needs to be done by interfacing directly with the OMS Service, not through Azure Security Center.
