### ISSUE TITLE
Get-ASCPolicy doesn't contain phone contact information

### ISSUE THREAD

**Issue by Javanite** [Microsoft/Azure-Security-Center#5]
In your ASC Policy alert settings, if you do not have a phone number specified, the API will not provide the securityContactPhone property when using Get-ASCPolicy. This causes Set-ASCPolicy to break because the property is missing.

This is a known issue and needs to be fixed on the ASC side. Posting here in case others run into it.

Workaround:
Manually specify a phone number in the portal so that the property contains data.

**Comment by kraghu306** [comment]
@Javanite I tried configuring SecurityContactPhone using Set-ASCPolicy and it works.
cmdlet: 
Set-ASCPolicy -PolicyName default -JSON (Build-ASCPolicy -PolicyName default -DataCollection On -Se
curityContactEmail abc@abc.com, bash@bash.com -SecurityContactPhone XXXXXXXXXX)

**Comment by Javanite** [comment]
Can you confirm if you had a phone number set in the ASC console before you ran the cmdlet? 

The issue is that Set-ASCPolicy will fail if you try setting a phone number when the phone number property is empty. If a number exists beforehand it will work.

**Comment by kraghu306** [comment]
@Javanite Yes, I tried the same. Initially, the phone number was empty in ASC console and tried to set via PowerShell cmdlet and it worked.

![asc](https://user-images.githubusercontent.com/1199532/41959221-f53ae996-7a09-11e8-82d3-1f827a08c655.png)

**Comment by Javanite** [comment]
Closing this issue as the new AzureRM.Security module is where further development of ASC cmdlets will take place. Please see the readme for links to the new documentation and code.
